### ISSUE TITLE
assignement 1.5 creation error

### ISSUE THREAD

**Issue by programlich** [AccelerationConsortium/ac-microcourses#107]
Container for codespaces seems to have a problem. Here is the log:

```
2024-10-21 21:14:42.013Z: Host information
2024-10-21 21:14:42.013Z: ----------------
2024-10-21 21:14:42.013Z: OS: Ubuntu 22.04.5 LTS (stable release)
2024-10-21 21:14:42.014Z: Image details: https://github.com/github/codespaces-host-images/blob/main/README.md
2024-10-21 21:14:42.014Z: ----------------

=================================================================================
2024-10-21 21:14:42.014Z: Configuration starting...
2024-10-21 21:14:42.064Z: Cloning...

=================================================================================
2024-10-21 21:14:53.618Z: Creating container...
2024-10-21 21:14:53.670Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/5-data-logging-programlich --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/5-data-logging-programlich/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-10-21 21:14:53.940Z: @devcontainers/cli 0.68.0. Node.js v18.20.4. linux 6.5.0-1025-azure x64.
2024-10-21 21:14:54.464Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1729545294458/Dockerfile-with-features -t vsc-5-data-logging-********-1b9190e5706a626c69b91b7bc80dd9f4008f4877c6cdd2388f9a08af6cdc6247 --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=none --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/5-data-logging-********
2024-10-21 21:14:58.174Z: ERROR: failed to receive status: rpc error: code = Canceled desc = context canceled
2024-10-21 21:14:58.181Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1729545294458/Dockerfile-with-features -t vsc-5-data-logging-programlich-1b9190e5706a626c69b91b7bc80dd9f4008f4877c6cdd2388f9a08af6cdc6247 --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=none --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/5-data-logging-programlich","description":"An error occurred building the image."}
2024-10-21 21:14:58.181Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1729545294458/Dockerfile-with-features -t vsc-5-data-logging-********-1b9190e5706a626c69b91b7bc80dd9f4008f4877c6cdd2388f9a08af6cdc6247 --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=none --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/5-data-logging-********
2024-10-21 21:14:58.183Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1729545294458/Dockerfile-with-features -t vsc-5-data-logging-programlich-1b9190e5706a626c69b91b7bc80dd9f4008f4877c6cdd2388f9a08af6cdc6247 --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=none --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/5-data-logging-programlich
2024-10-21 21:14:58.183Z:     at FtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:466:1933)
2024-10-21 21:14:58.183Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-21 21:14:58.183Z:     at async Pm (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1896)
2024-10-21 21:14:58.183Z:     at async NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:610)
2024-10-21 21:14:58.184Z:     at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
2024-10-21 21:14:58.184Z:     at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
2024-10-21 21:14:58.184Z:     at async prA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:663:200)
2024-10-21 21:14:58.185Z:     at async drA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:662:14706)
2024-10-21 21:14:58.196Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2024-10-21 21:14:58.202Z: Failed to create container.
=================================================================================
2024-10-21 21:14:58.202Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1729545294458/Dockerfile-with-features -t vsc-5-data-logging-programlich-1b9190e5706a626c69b91b7bc80dd9f4008f4877c6cdd2388f9a08af6cdc6247 --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=none --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/5-data-logging-programlich
2024-10-21 21:14:58.205Z: Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)

====================================== ERROR ====================================
2024-10-21 21:14:58.221Z: Container creation failed.
=================================================================================
2024-10-21 21:14:58.241Z: 

===================================== WARNING ===================================
2024-10-21 21:14:58.241Z: Creating recovery container.
=================================================================================

=================================================================================
2024-10-21 21:16:48.009Z: Creating container...
2024-10-21 21:16:48.032Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/5-data-logging-programlich --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/5-data-logging-programlich/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-10-21 21:16:48.213Z: @devcontainers/cli 0.68.0. Node.js v18.20.4. linux 6.5.0-1025-azure x64.
2024-10-21 21:16:48.587Z: $alpine -c echo Container started
2024-10-21 21:16:48.620Z: Unable to find image 'mcr.microsoft.com/devcontainers/base:alpine' locally
2024-10-21 21:16:48.750Z: alpine: 2024-10-21 21:16:48.751Z: Pulling from devcontainers/base
2024-10-21 21:16:48.793Z: 
[1A2024-10-21 21:16:48.794Z: [2K
43c4264eed91: Pulling fs layer 
[1B
[1A[2K
f40462439694: Pulling fs layer 
[1B
[1A[2K
78f82a04246d: 2024-10-21 21:16:48.798Z: Pulling fs layer 
[1B
[1A[2K
ab30627c2e5e: Pulling fs layer 
[1B
[1A[2K
1c6e677dc7f6: Pulling fs layer 
[1B
[1A[2K
90218552dd33: Pulling fs layer 
[1B
[1A[2K
43d7c7b4c7f6: Pulling fs layer 
[1B[4A[2K
ab30627c2e5e: Waiting 
[4B[3A[2K
1c6e677dc7f6: Waiting 
[3B[2A[2K
90218552dd33: Waiting 
[2B[1A[2K
43d7c7b4c7f6: Waiting 
[1B2024-10-21 21:16:48.870Z: [5A[2K
78f82a04246d: 2024-10-21 21:16:48.871Z: Downloading     134B/134B
[5B[5A[2K
78f82a04246d: Verifying Checksum 
[5B[5A[2K
78f82a04246d: Download complete 
[5B2024-10-21 21:16:48.875Z: [7A[2K
43c4264eed91: Downloading  48.34kB/3.624MB
[7B2024-10-21 21:16:48.888Z: [6A[2K
f40462439694: Downloading     409B/409B
[6B[6A[2K
f40462439694: Verifying Checksum 
[6B2024-10-21 21:16:48.889Z: [6A[2K
f40462439694: Download complete 
[6B2024-10-21 21:16:48.905Z: [7A[2K
43c4264eed91: Downloading  3.624MB/3.624MB
[7B[7A[2K
43c4264eed91: Verifying Checksum 
[7B[7A[2K
43c4264eed91: Download complete 
[7B2024-10-21 21:16:48.939Z: [7A[2K
43c4264eed91: 2024-10-21 21:16:48.940Z: Extracting  65.54kB/3.624MB
[7B2024-10-21 21:16:48.972Z: [4A[2K
ab30627c2e5e: Downloading     223B/223B
[4B2024-10-21 21:16:48.977Z: [4A[2K
ab30627c2e5e: Verifying Checksum 
[4B[4A[2K
ab30627c2e5e: Download complete 
[4B2024-10-21 21:16:48.983Z: [3A[2K
1c6e677dc7f6: Downloading     234B/234B
[3B[3A[2K
1c6e677dc7f6: Verifying Checksum 
[3B[3A[2K
1c6e677dc7f6: Download complete 
[3B2024-10-21 21:16:49.006Z: [2A[2K
90218552dd33: Downloading  538.9kB/228.2MB
[2B2024-10-21 21:16:49.105Z: [1A[2K
43d7c7b4c7f6: Downloading  440.6kB/43.39MB
[1B2024-10-21 21:16:49.121Z: [2A2024-10-21 21:16:49.123Z: [2K2024-10-21 21:16:49.125Z: 
2024-10-21 21:16:49.127Z: 90218552dd33: 2024-10-21 21:16:49.128Z: Downloading  15.12MB/228.2MB
2024-10-21 21:16:49.130Z: [2B2024-10-21 21:16:49.193Z: [1A2024-10-21 21:16:49.195Z: [2K
43d7c7b4c7f6: 2024-10-21 21:16:49.196Z: Downloading  15.04MB/43.39MB
2024-10-21 21:16:49.199Z: [1B2024-10-21 21:16:49.235Z: [2A[2K
90218552dd33: Downloading   30.8MB/228.2MB
[2B2024-10-21 21:16:49.294Z: [1A[2K
2024-10-21 21:16:49.296Z: 43d7c7b4c7f6: Downloading  32.74MB/43.39MB
[1B2024-10-21 21:16:49.313Z: [2A2024-10-21 21:16:49.317Z: [2K2024-10-21 21:16:49.318Z: 
2024-10-21 21:16:49.319Z: 90218552dd33: 2024-10-21 21:16:49.320Z: Downloading   48.1MB/228.2MB
2024-10-21 21:16:49.321Z: [2B2024-10-21 21:16:49.359Z: [1A2024-10-21 21:16:49.359Z: [2K2024-10-21 21:16:49.359Z: 
2024-10-21 21:16:49.359Z: 43d7c7b4c7f6: 2024-10-21 21:16:49.359Z: Verifying Checksum 
2024-10-21 21:16:49.359Z: [1B2024-10-21 21:16:49.360Z: [1A2024-10-21 21:16:49.360Z: [2K2024-10-21 21:16:49.360Z: 
2024-10-21 21:16:49.360Z: 43d7c7b4c7f6: 2024-10-21 21:16:49.360Z: Download complete 
2024-10-21 21:16:49.360Z: [1B2024-10-21 21:16:49.414Z: [2A2024-10-21 21:16:49.414Z: [2K2024-10-21 21:16:49.415Z: 
2024-10-21 21:16:49.415Z: 90218552dd33: 2024-10-21 21:16:49.415Z: Downloading  73.52MB/228.2MB
2024-10-21 21:16:49.416Z: [2B2024-10-21 21:16:49.524Z: [2A2024-10-21 21:16:49.525Z: [2K2024-10-21 21:16:49.533Z: 
2024-10-21 21:16:49.535Z: 90218552dd33: Downloading  98.93MB/228.2MB
[2B2024-10-21 21:16:49.617Z: [2A[2K
90218552dd33: Downloading  124.3MB/228.2MB
[2B2024-10-21 21:16:49.717Z: [2A[2K
2024-10-21 21:16:49.717Z: 90218552dd33: Downloading  149.2MB/228.2MB
[2B2024-10-21 21:16:49.819Z: [2A[2K
2024-10-21 21:16:49.820Z: 90218552dd33: 2024-10-21 21:16:49.821Z: Downloading  176.2MB/228.2MB
2024-10-21 21:16:49.822Z: [2B2024-10-21 21:16:49.919Z: [2A[2K
90218552dd33: Downloading  203.8MB/228.2MB
[2B2024-10-21 21:16:50.012Z: [2A[2K
90218552dd33: Verifying Checksum 
[2B2024-10-21 21:16:50.012Z: [2A[2K
90218552dd33: Download complete 
[2B2024-10-21 21:16:52.350Z: [7A[2K
43c4264eed91: Extracting  262.1kB/3.624MB
[7B2024-10-21 21:16:52.418Z: [7A[2K
2024-10-21 21:16:52.419Z: 43c4264eed91: Extracting  3.624MB/3.624MB
[7B2024-10-21 21:16:52.527Z: [7A[2K
43c4264eed91: Pull complete 
[7B2024-10-21 21:16:52.558Z: [6A2024-10-21 21:16:52.559Z: [2K2024-10-21 21:16:52.560Z: 
2024-10-21 21:16:52.562Z: f40462439694: Extracting     409B/409B
2024-10-21 21:16:52.562Z: [6B2024-10-21 21:16:52.562Z: [6A[2K
f40462439694: Extracting     409B/409B
[6B2024-10-21 21:16:55.587Z: [6A2024-10-21 21:16:55.588Z: [2K
f40462439694: Pull complete 
[6B2024-10-21 21:16:55.655Z: [5A[2K
78f82a04246d: Extracting     134B/134B
[5B2024-10-21 21:16:55.656Z: [5A[2K
78f82a04246d: Extracting     134B/134B
[5B2024-10-21 21:16:55.821Z: [5A[2K
78f82a04246d: Pull complete 
[5B2024-10-21 21:16:55.842Z: [4A[2K
ab30627c2e5e: Extracting     223B/223B
[4B2024-10-21 21:16:55.843Z: [4A[2K
ab30627c2e5e: Extracting     223B/223B
[4B2024-10-21 21:16:55.994Z: [4A[2K
ab30627c2e5e: Pull complete 
[4B2024-10-21 21:16:56.021Z: [3A[2K
1c6e677dc7f6: Extracting     234B/234B
[3B2024-10-21 21:16:56.023Z: [3A[2K
1c6e677dc7f6: Extracting     234B/234B
[3B2024-10-21 21:16:56.169Z: [3A[2K
1c6e677dc7f6: Pull complete 
[3B2024-10-21 21:16:56.252Z: [2A[2K
90218552dd33: Extracting  557.1kB/228.2MB
[2B2024-10-21 21:16:56.359Z: [2A[2K
90218552dd33: Extracting  3.342MB/228.2MB
[2B2024-10-21 21:16:56.464Z: [2A[2K
90218552dd33: Extracting  10.03MB/228.2MB
[2B2024-10-21 21:16:56.563Z: [2A[2K
90218552dd33: Extracting   15.6MB/228.2MB
[2B2024-10-21 21:16:56.685Z: [2A[2K2024-10-21 21:16:56.686Z: 
90218552dd33: Extracting  21.17MB/228.2MB
[2B2024-10-21 21:16:56.801Z: [2A[2K
90218552dd33: 2024-10-21 21:16:56.801Z: Extracting  22.28MB/228.2MB
[2B2024-10-21 21:16:56.913Z: [2A[2K
90218552dd33: Extracting  22.84MB/228.2MB
[2B2024-10-21 21:16:57.080Z: [2A[2K
90218552dd33: Extracting  23.95MB/228.2MB
[2B2024-10-21 21:16:57.225Z: [2A[2K
90218552dd33: Extracting   27.3MB/228.2MB
[2B2024-10-21 21:16:57.335Z: [2A[2K
90218552dd33: Extracting  28.41MB/228.2MB
[2B2024-10-21 21:16:57.447Z: [2A[2K
90218552dd33: Extracting  33.98MB/228.2MB
[2B2024-10-21 21:16:57.550Z: [2A[2K
90218552dd33: Extracting  39.55MB/228.2MB
[2B2024-10-21 21:16:57.662Z: [2A[2K
90218552dd33: Extracting  45.12MB/228.2MB
[2B2024-10-21 21:16:57.764Z: [2A[2K
90218552dd33: 2024-10-21 21:16:57.764Z: Extracting  49.58MB/228.2MB
[2B2024-10-21 21:16:57.872Z: [2A[2K
90218552dd33: Extracting  52.36MB/228.2MB
[2B2024-10-21 21:16:57.976Z: [2A[2K
90218552dd33: Extracting  55.71MB/228.2MB
[2B2024-10-21 21:16:58.087Z: [2A[2K
90218552dd33: Extracting  58.49MB/228.2MB
[2B2024-10-21 21:16:58.190Z: [2A[2K
90218552dd33: Extracting  66.85MB/228.2MB
[2B2024-10-21 21:16:58.290Z: [2A[2K
90218552dd33: Extracting  75.76MB/228.2MB
[2B2024-10-21 21:16:58.392Z: [2A[2K
90218552dd33: Extracting  85.79MB/228.2MB
[2B2024-10-21 21:16:58.493Z: [2A[2K
90218552dd33: Extracting  95.81MB/228.2MB
[2B2024-10-21 21:16:58.596Z: [2A[2K
90218552dd33: Extracting  106.4MB/228.2MB
2024-10-21 21:16:58.597Z: [2B2024-10-21 21:16:58.714Z: [2A[2K
90218552dd33: Extracting  111.4MB/228.2MB
[2B2024-10-21 21:16:58.821Z: [2A[2K
90218552dd33: Extracting  114.2MB/228.2MB
[2B2024-10-21 21:16:58.951Z: [2A[2K
90218552dd33: Extracting    117MB/228.2MB
[2B2024-10-21 21:16:59.075Z: [2A[2K
90218552dd33: Extracting  118.7MB/228.2MB
[2B2024-10-21 21:16:59.176Z: [2A[2K
90218552dd33: Extracting  119.8MB/228.2MB
[2B2024-10-21 21:16:59.280Z: [2A[2K
90218552dd33: Extracting  126.5MB/228.2MB
[2B2024-10-21 21:16:59.394Z: [2A[2K
90218552dd33: Extracting    132MB/228.2MB
[2B2024-10-21 21:16:59.502Z: [2A2024-10-21 21:16:59.502Z: [2K
90218552dd33: Extracting  139.3MB/228.2MB
[2B2024-10-21 21:16:59.606Z: [2A[2K
2024-10-21 21:16:59.607Z: 90218552dd33: Extracting  145.4MB/228.2MB
[2B2024-10-21 21:16:59.706Z: [2A[2K2024-10-21 21:16:59.707Z: 
90218552dd33: Extracting  149.8MB/228.2MB
[2B2024-10-21 21:16:59.812Z: [2A[2K2024-10-21 21:16:59.812Z: 
90218552dd33: Extracting    156MB/228.2MB
[2B2024-10-21 21:16:59.912Z: [2A[2K2024-10-21 21:16:59.913Z: 
90218552dd33: Extracting  161.5MB/228.2MB
[2B2024-10-21 21:17:00.021Z: [2A[2K2024-10-21 21:17:00.021Z: 
90218552dd33: Extracting  168.8MB/228.2MB
[2B2024-10-21 21:17:00.129Z: [2A[2K2024-10-21 21:17:00.129Z: 
90218552dd33: Extracting    176MB/228.2MB
[2B2024-10-21 21:17:00.231Z: [2A2024-10-21 21:17:00.231Z: [2K
90218552dd33: Extracting  182.7MB/228.2MB
[2B2024-10-21 21:17:00.334Z: [2A2024-10-21 21:17:00.334Z: [2K
90218552dd33: Extracting  188.8MB/228.2MB
[2B2024-10-21 21:17:00.437Z: [2A2024-10-21 21:17:00.437Z: [2K
90218552dd33: Extracting  195.5MB/228.2MB
[2B2024-10-21 21:17:00.547Z: [2A[2K2024-10-21 21:17:00.547Z: 
90218552dd33: Extracting  201.7MB/228.2MB
[2B2024-10-21 21:17:00.660Z: [2A[2K
90218552dd33: Extracting  208.3MB/228.2MB
[2B2024-10-21 21:17:00.764Z: [2A[2K
90218552dd33: Extracting  215.6MB/228.2MB
2024-10-21 21:17:00.765Z: [2B2024-10-21 21:17:00.937Z: [2A[2K
90218552dd33: 2024-10-21 21:17:00.937Z: Extracting  219.5MB/228.2MB
[2B2024-10-21 21:17:01.044Z: [2A[2K2024-10-21 21:17:01.046Z: 
90218552dd33: Extracting  220.6MB/228.2MB
[2B2024-10-21 21:17:01.199Z: [2A[2K
90218552dd33: Extracting  222.3MB/228.2MB
[2B2024-10-21 21:17:01.307Z: [2A[2K
90218552dd33: Extracting  222.8MB/228.2MB
[2B2024-10-21 21:17:01.421Z: [2A[2K
90218552dd33: Extracting  223.4MB/228.2MB
[2B2024-10-21 21:17:01.715Z: [2A[2K2024-10-21 21:17:01.715Z: 
90218552dd33: Extracting  223.9MB/228.2MB
[2B2024-10-21 21:17:01.821Z: [2A[2K2024-10-21 21:17:01.821Z: 
90218552dd33: Extracting  225.1MB/228.2MB
[2B2024-10-21 21:17:02.056Z: [2A[2K
90218552dd33: Extracting  225.6MB/228.2MB
[2B2024-10-21 21:17:02.502Z: [2A[2K2024-10-21 21:17:02.503Z: 
90218552dd33: Extracting  226.2MB/228.2MB
[2B2024-10-21 21:17:02.538Z: [2A[2K
90218552dd33: Extracting  228.2MB/228.2MB
[2B2024-10-21 21:17:07.931Z: [2A[2K
90218552dd33: Pull complete 
[2B2024-10-21 21:17:08.011Z: [1A2024-10-21 21:17:08.012Z: [2K
43d7c7b4c7f6: Extracting  458.8kB/43.39MB
[1B2024-10-21 21:17:08.135Z: [1A[2K2024-10-21 21:17:08.136Z: 
43d7c7b4c7f6: Extracting  4.588MB/43.39MB
[1B2024-10-21 21:17:08.267Z: [1A[2K
2024-10-21 21:17:08.268Z: 43d7c7b4c7f6: Extracting  5.046MB/43.39MB
[1B2024-10-21 21:17:08.400Z: [1A[2K
2024-10-21 21:17:08.400Z: 43d7c7b4c7f6: Extracting  7.799MB/43.39MB
[1B2024-10-21 21:17:08.587Z: [1A[2K
43d7c7b4c7f6: Extracting  12.39MB/43.39MB
[1B2024-10-21 21:17:08.712Z: [1A[2K
43d7c7b4c7f6: Extracting  12.85MB/43.39MB
[1B2024-10-21 21:17:08.813Z: [1A[2K
43d7c7b4c7f6: Extracting  16.52MB/43.39MB
[1B2024-10-21 21:17:08.916Z: [1A[2K
43d7c7b4c7f6: Extracting  21.56MB/43.39MB
[1B2024-10-21 21:17:09.024Z: [1A[2K2024-10-21 21:17:09.024Z: 
43d7c7b4c7f6: Extracting  26.61MB/43.39MB
[1B2024-10-21 21:17:09.183Z: [1A[2K
2024-10-21 21:17:09.183Z: 43d7c7b4c7f6: Extracting  29.36MB/43.39MB
[1B2024-10-21 21:17:09.304Z: [1A[2K
2024-10-21 21:17:09.304Z: 43d7c7b4c7f6: Extracting  29.82MB/43.39MB
[1B2024-10-21 21:17:09.451Z: [1A[2K
43d7c7b4c7f6: 2024-10-21 21:17:09.451Z: Extracting  30.74MB/43.39MB
[1B2024-10-21 21:17:09.560Z: [1A[2K
43d7c7b4c7f6: Extracting   31.2MB/43.39MB
[1B2024-10-21 21:17:09.677Z: [1A[2K
43d7c7b4c7f6: Extracting  31.65MB/43.39MB
[1B2024-10-21 21:17:09.830Z: [1A[2K
43d7c7b4c7f6: Extracting  33.03MB/43.39MB
[1B2024-10-21 21:17:10.051Z: [1A[2K
43d7c7b4c7f6: Extracting  36.24MB/43.39MB
[1B2024-10-21 21:17:10.186Z: [1A[2K
43d7c7b4c7f6: Extracting  38.99MB/43.39MB
2024-10-21 21:17:10.186Z: [1B2024-10-21 21:17:10.292Z: [1A[2K
43d7c7b4c7f6: Extracting  39.91MB/43.39MB
[1B2024-10-21 21:17:10.449Z: [1A[2K
43d7c7b4c7f6: Extracting  40.83MB/43.39MB
[1B2024-10-21 21:17:10.552Z: [1A[2K
43d7c7b4c7f6: Extracting  41.29MB/43.39MB
[1B2024-10-21 21:17:10.579Z: [1A[2K
43d7c7b4c7f6: Extracting  43.39MB/43.39MB
[1B2024-10-21 21:17:12.344Z: [1A[2K
43d7c7b4c7f6: Pull complete 
[1B2024-10-21 21:17:12.394Z: Digest: sha256:b7a03802a7af5b3bc45e567a697ce4747c470296f900fadce6f9bdc02296a386
2024-10-21 21:17:12.425Z: Status: Downloaded newer image for mcr.microsoft.com/devcontainers/base:alpine
2024-10-21 21:17:12.859Z: Container started
2024-10-21 21:17:13.123Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/5-data-logging-programlich
2024-10-21 21:17:13.132Z: devcontainer process exited with exit code 0

=================================================================================
2024-10-21 21:17:14.157Z: Running blocking commands...
2024-10-21 21:17:14.187Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/5-data-logging-programlich --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/5-data-logging-programlich/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-10-21 21:17:14.410Z: @devcontainers/cli 0.68.0. Node.js v18.20.4. linux 6.5.0-1025-azure x64.
2024-10-21 21:17:14.633Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/5-data-logging-programlich
2024-10-21 21:17:14.643Z: devcontainer process exited with exit code 0

=================================================================================
2024-10-21 21:17:14.650Z: Configuring codespace...

=================================================================================
2024-10-21 21:17:14.714Z: Finished configuring codespace.

```

**Comment by programlich** [comment]
I am currently in the assignment for 1.6 and there the same error comes up. Do you need the logs? Also I am in the AC office today, so we can debug together, if that´s of any help to you
